// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/73110d92bdab2367e326f297bef3574285cba329/ng-cordova/deviceOrientation.d.ts
declare namespace ngCordova {

  export interface IDeviceOrientationHeading {
      magneticHeading: number;
      trueHeading?: number;
      headingAccuracy?: number;
      timestamp?: number;
  }

  export interface IDeviceOrientationWatchOptions {
      frequency?: number;
      filter?: number;
  }

  export interface IDeviceOrientationWatchPromise extends ng.IPromise<IDeviceOrientationHeading> {
      watchID: number;
      cancel: () => void;
      clearWatch: (watchId?: number) => void;
  }

  export interface IDeviceOrientationService {
      getCurrentHeading(): ng.IPromise<IDeviceOrientationHeading>;
      watchHeading(options: IDeviceOrientationWatchOptions): IDeviceOrientationWatchPromise;
      clearWatch(watchID: number): void;
  }

}
